In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Indian_Insurance_Data.csv')

In [3]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,50,57,176,29.90,False,Agra,Factory Worker,Medium
1,56,90,168,19.22,False,Allahabad,Businessman,Medium
2,26,87,178,36.95,False,Srinagar,Sales Manager,Low
3,34,73,162,14.75,False,Meerut,Banker,Low
4,43,47,192,19.32,True,Varanasi,Marketing Manager,High

In [4]:
df['city'].unique()

array(['Agra', 'Allahabad', 'Srinagar', 'Meerut', 'Varanasi', 'Hyderabad',
       'Ahmedabad', 'Chennai', 'Amritsar', 'Vadodara', 'Lucknow',
       'Bhopal', 'Mumbai', 'Ludhiana', 'Rajkot', 'Surat', 'Ghaziabad',
       'Ranchi', 'Pune', 'Kanpur', 'Nagpur', 'Faridabad', 'Bangalore',
       'Jaipur', 'Kolkata', 'Nashik', 'Patna', 'Indore', 'Delhi',
       'Visakhapatnam'], dtype=object)

In [5]:
df['occupation'].unique()

array(['Factory Worker', 'Businessman', 'Sales Manager', 'Banker',
       'Marketing Manager', 'Insurance Agent', 'HR Manager', 'Pharmacist',
       'Teacher', 'Software Engineer', 'Consultant', 'Driver',
       'Shop Owner', 'Nurse', 'Accountant', 'Government Employee',
       'Architect', 'Engineer', 'Real Estate Agent', 'Civil Servant',
       'Plumber', 'Retail Manager', 'Chef', 'Electrician', 'Carpenter',
       'Doctor', 'Lab Technician', 'Data Analyst', 'Lawyer',
       'Content Writer'], dtype=object)

In [6]:
def age_group(age):
    if age < 18:
        return 'Junior'
    elif age < 45:
        return 'Middle Age'
    else:
        return 'Senior'

In [7]:
df['age_group'] = df['age'].apply(age_group)

In [8]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,age_group
0,50,57,176,29.90,False,Agra,Factory Worker,Medium,Senior
1,56,90,168,19.22,False,Allahabad,Businessman,Medium,Senior
2,26,87,178,36.95,False,Srinagar,Sales Manager,Low,Middle Age
3,34,73,162,14.75,False,Meerut,Banker,Low,Middle Age
4,43,47,192,19.32,True,Varanasi,Marketing Manager,High,Middle Age

In [12]:
df['height'] = df['height']/100

In [13]:
df['bmi'] = df['weight']/(df['height'])**2

In [14]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,age_group,bmi
0,50,57,1.76,29.90,False,Agra,Factory Worker,Medium,Senior,18.401343
1,56,90,1.68,19.22,False,Allahabad,Businessman,Medium,Senior,31.887755
2,26,87,1.78,36.95,False,Srinagar,Sales Manager,Low,Middle Age,27.458654
3,34,73,1.62,14.75,False,Meerut,Banker,Low,Middle Age,27.815882
4,43,47,1.92,19.32,True,Varanasi,Marketing Manager,High,Middle Age,12.749566

In [19]:
def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif bmi < 24.9:
        return 'Normal'
    elif bmi < 29.9:
        return 'Overweight'
    else:
        return 'Obese'

In [20]:
df['bmi_category'] = df['bmi'].apply(bmi_category)

In [21]:
df.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,age_group,bmi,bmi_category
2436,59,49,1.77,28.16,False,Faridabad,Shop Owner,High,Senior,15.640461,Underweight
1078,33,96,1.64,33.30,False,Lucknow,Lab Technician,Medium,Middle Age,35.693040,Obese
2652,57,49,1.56,38.21,False,Srinagar,Banker,Medium,Senior,20.134780,Normal
2080,24,83,1.82,25.54,False,Ahmedabad,Doctor,Low,Middle Age,25.057360,Overweight
1626,31,76,1.81,25.24,False,Chennai,Nurse,Low,Middle Age,23.198315,Normal

In [30]:
df['smoker'].dtype

dtype('bool')

In [37]:
def lifestyle_risk(row):

    bmi = row['bmi_category']
    smoker = row['smoker']

    if bmi == 'Normal' and smoker == False:
        return 'low'

    elif bmi == 'Underweight' and smoker == False:
        return 'medium'

    elif bmi == 'Overweight' and smoker == False:
        return 'medium'

    elif bmi == 'Normal' and smoker == True:
        return 'medium'

    elif bmi == 'Obese' and smoker == False:
        return 'high'

    elif bmi == 'Underweight' and smoker == True:
        return 'high'

    elif bmi == 'Overweight' and smoker == True:
        return 'high'

    elif bmi == 'Obese' and smoker == True:
        return 'high'


df['lifestyle_risk'] = df.apply(lifestyle_risk, axis=1)

In [39]:
df.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,age_group,bmi,bmi_category,lifestyle_risk
3308,63,52,1.83,9.12,False,Hyderabad,Doctor,Medium,Senior,15.527487,Underweight,medium
1785,34,66,1.95,42.41,True,Allahabad,Lab Technician,High,Middle Age,17.357002,Underweight,high
612,54,74,1.62,40.57,False,Allahabad,Electrician,Medium,Senior,28.196921,Overweight,medium
2503,42,76,1.85,2.46,False,Nashik,Carpenter,Low,Middle Age,22.205990,Normal,low
3104,40,99,1.76,47.91,False,Bangalore,Banker,Medium,Middle Age,31.960227,Obese,high

In [42]:
df['city'].unique()

array(['Agra', 'Allahabad', 'Srinagar', 'Meerut', 'Varanasi', 'Hyderabad',
       'Ahmedabad', 'Chennai', 'Amritsar', 'Vadodara', 'Lucknow',
       'Bhopal', 'Mumbai', 'Ludhiana', 'Rajkot', 'Surat', 'Ghaziabad',
       'Ranchi', 'Pune', 'Kanpur', 'Nagpur', 'Faridabad', 'Bangalore',
       'Jaipur', 'Kolkata', 'Nashik', 'Patna', 'Indore', 'Delhi',
       'Visakhapatnam'], dtype=object)

In [43]:
def city_tier(city):

    tier_1 = [
        'Mumbai',
        'Delhi',
        'Bangalore',
        'Hyderabad',
        'Chennai',
        'Kolkata',
        'Pune',
        'Ahmedabad',
        'Ghaziabad',
        'Faridabad'
    ]

    tier_2 = [
        'Jaipur',
        'Lucknow',
        'Kanpur',
        'Nagpur',
        'Indore',
        'Bhopal',
        'Patna',
        'Vadodara',
        'Surat',
        'Nashik',
        'Visakhapatnam',
        'Ranchi',
        'Ludhiana',
        'Agra',
        'Varanasi',
        'Rajkot',
        'Meerut',
        'Amritsar'
    ]

    tier_3 = [
        'Allahabad',
        'Srinagar'
    ]

    if city in tier_1:
        return '1'

    elif city in tier_2:
        return '2'

    elif city in tier_3:
        return '3'

    else:
        return 'Unknown'

In [44]:
df['city_tier'] = df['city'].apply(city_tier)

In [45]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,age_group,bmi,bmi_category,lifestyle_risk,city_tier
0,50,57,1.76,29.90,False,Agra,Factory Worker,Medium,Senior,18.401343,Underweight,medium,2
1,56,90,1.68,19.22,False,Allahabad,Businessman,Medium,Senior,31.887755,Obese,high,3
2,26,87,1.78,36.95,False,Srinagar,Sales Manager,Low,Middle Age,27.458654,Overweight,medium,3
3,34,73,1.62,14.75,False,Meerut,Banker,Low,Middle Age,27.815882,Overweight,medium,2
4,43,47,1.92,19.32,True,Varanasi,Marketing Manager,High,Middle Age,12.749566,Underweight,high,2

In [49]:
 df1 = df.drop(labels =  ['weight', 'height', 'smoker', 'age', 'city', 'bmi_category'], axis = 1)

In [50]:
df1.to_csv('insurance_cleaned.csv', index=False)